services:
  php:
    image: dunglas/frankenphp
    build: .docker/frankenphp/
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true

  database:
    image: postgres:15-alpine
    build: .docker/postgres/
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: chronicle-keeper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
