services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/frankenphp/Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DATABASE_TYPE: PgSql
      DATABASE_CONNECTION: pgsql:host=${POSTGRES_HOST:-database};port=${POSTGRES_PORT:-5432};dbname=${POSTGRES_DB:-chronicle-keeper};user=${POSTGRES_USER:-app};password=${POSTGRES_PASSWORD:-app}
      DATABASE_URL: pgsql://${POSTGRES_USER:-${POSTGRES_PASSWORD:-app}}:app@${POSTGRES_HOST:-database}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-chronicle-keeper}?serverVersion=15&charset=utf8
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  database:
    profiles: ["dev", "all"]
    image: postgres:15-alpine
    build:
        context: .
        dockerfile: .docker/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: chronicle-keeper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  database_test:
    profiles: ["test", "all"]
    image: postgres:15-alpine
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: app_test
      POSTGRES_PASSWORD: app_test
      POSTGRES_DB: chronicle-keeper-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./.docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  postgres_test_data:
