services:
  ChronicleKeeper\Shared\Application\Query\QueryService:
    autowire: true
    autoconfigure: true
    public: true

  ChronicleKeeper\Library\Infrastructure\Repository\FilesystemVectorImageRepository:
    autowire: true
    autoconfigure: true
    public: true
