services:
  ChronicleKeeper\Shared\Infrastructure\Persistence\Filesystem\Contracts\FileAccess:
    class: ChronicleKeeper\Test\Shared\Infrastructure\Persistence\Filesystem\FileAccessDouble

  ChronicleKeeper\Shared\Infrastructure\LLMChain\LLMChainFactory:
    class: ChronicleKeeper\Test\Shared\Infrastructure\LLMChain\LLMChainFactoryDouble
