services:
  ChronicleKeeper\Shared\Application\Query\QueryService:
    autowire: true
    autoconfigure: true
    public: true

  ChronicleKeeper\Library\Infrastructure\Repository\FilesystemVectorImageRepository:
    autowire: true
    autoconfigure: true
    public: true

  ChronicleKeeper\Library\Infrastructure\Repository\FilesystemImageRepository:
    autowire: true
    autoconfigure: true
    public: true

  ChronicleKeeper\Library\Infrastructure\Repository\FilesystemDirectoryRepository:
    autowire: true
    autoconfigure: true
    public: true

  ChronicleKeeper\Shared\Infrastructure\LLMChain\EmbeddingCalculator:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\Serializer\Serializer:
    parent: serializer
    public: true
