services:
  ChronicleKeeper\Shared\Infrastructure\Persistence\Filesystem\Contracts\FileAccess:
    class: ChronicleKeeper\Test\Shared\Infrastructure\Persistence\Filesystem\FileAccessDouble

  ChronicleKeeper\Shared\Infrastructure\Persistence\Filesystem\Contracts\Finder:
    class: ChronicleKeeper\Test\Shared\Infrastructure\Persistence\Filesystem\FinderDouble
