SHELL := /bin/bash
.PHONY: *

# Environment handling
# (Removed custom env setup logic; rely on Symfony's .env loading)

setup-database: ## setup the database
	 $(PHP) bin/console app:db:init --force -vvv
