name: Build Symfony CLI Package for Windows

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  symfony-cli-windows:
    name: build symfony-cli-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: do application build
        run: make symfony-cli

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          command: 'mv build/ ChronicleKeeper-Server-Windows-${{ github.ref_name }}/'
          path: "ChronicleKeeper-Server-Windows-${{ github.ref_name }}"
          filename: "ChronicleKeeper-Server-Windows-${{ github.ref_name }}.zip"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: "ChronicleKeeper-Server-Windows-${{ github.ref_name }}.zip"
